# Generated by Django 6.0.7 on 2026-07-19 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('default_unit', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'składnik',
                'verbose_name_plural': 'składniki',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('preparation_time', models.PositiveIntegerField(default=0, help_text='Czas przygotowania w minutach')),
                ('servings', models.PositiveIntegerField(default=1)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='recipes/')),
            ],
            options={
                'verbose_name': 'przepis',
                'verbose_name_plural': 'przepisy',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'składnik przepisu',
                'verbose_name_plural': 'składniki przepisów',
                'ordering': ['ingredient__name'],
                'unique_together': {('recipe', 'ingredient')},
            },
        ),
    ]
