# Generated by Django 6.0.7 on 2026-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(blank=True, help_text='Kroki przygotowania (każdy krok w nowej linii)'),
        ),
    ]
