# Generated by Django 6.0.7 on 2026-07-24 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_add_instructions_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.DecimalField(decimal_places=2, default=0, help_text='Kalorie (kcal) na 100g/100ml', max_digits=7, verbose_name='kalorie (kcal)')),
                ('protein', models.DecimalField(decimal_places=2, default=0, help_text='Białko (g) na 100g/100ml', max_digits=6, verbose_name='białko (g)')),
                ('carbohydrates', models.DecimalField(decimal_places=2, default=0, help_text='Węglowodany (g) na 100g/100ml', max_digits=6, verbose_name='węglowodany (g)')),
                ('fat', models.DecimalField(decimal_places=2, default=0, help_text='Tłuszcze (g) na 100g/100ml', max_digits=6, verbose_name='tłuszcze (g)')),
                ('fiber', models.DecimalField(decimal_places=2, default=0, help_text='Błonnik (g) na 100g/100ml', max_digits=6, verbose_name='błonnik (g)')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition', to='recipes.ingredient', verbose_name='składnik')),
            ],
            options={
                'verbose_name': 'wartości odżywcze',
                'verbose_name_plural': 'wartości odżywcze',
            },
        ),
    ]
