# Generated by Django 6.0.7 on 2026-07-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('week_start', models.DateField(help_text='Pierwszy dzień tygodnia dla tego planu')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'plan tygodnia',
                'verbose_name_plural': 'plany tygodniowe',
                'ordering': ['-week_start', 'name'],
            },
        ),
    ]
