# Generated by Django 6.0.7 on 2026-07-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ['name', 'day_of_week']},
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mealplan',
            name='week_start',
        ),
        migrations.AddField(
            model_name='mealplan',
            name='day_of_week',
            field=models.CharField(choices=[('Poniedziałek', 'Poniedziałek'), ('Wtorek', 'Wtorek'), ('Środa', 'Środa'), ('Czwartek', 'Czwartek'), ('Piątek', 'Piątek'), ('Sobota', 'Sobota'), ('Niedziela', 'Niedziela')], default=None, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipe_dinner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealplan_dinner', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipe_dinner_alternative',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealplan_dinner_alternative', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='mealplan',
            name='recipe_supper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mealplan_supper', to='recipes.recipe'),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
